name: Deploy
on: push
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            # Checks out a copy of your repository
            - name: Checkout code
              uses: actions/checkout@v2

            # Runs the Super-Linter action
            - name: Run Super-Linter
              uses: github/super-linter@v3
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
